linters:
  enable:
    - govet
    - gosec
    - ineffassign
    - unparam
    - revive

run:
  timeout: 5m

issues:
  exclude:
    - test-files

golint:
  min_confidence: 0.8  # Порог уверенности для ошибок golint

# Правила для govet (включает правила для именования)
govet:
  checks: all

# Правила для gosec (проверка на уязвимости)
gosec:
  enable:
    - G101  # Ошибка использования неподходящего случайного числа

# Правила для ineffassign и unparam (проверка на неиспользуемые переменные)
ineffassign:
  ignore-generated-files: true

unparam:
  ignore-generated-files: true

