// Code generated by MockGen. DO NOT EDIT.
// Source: gophkeeper/internal/repositories/connection (interfaces: ConnectionInfoKeeper)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockConnectionInfoKeeper is a mock of ConnectionInfoKeeper interface.
type MockConnectionInfoKeeper struct {
	ctrl     *gomock.Controller
	recorder *MockConnectionInfoKeeperMockRecorder
}

// MockConnectionInfoKeeperMockRecorder is the mock recorder for MockConnectionInfoKeeper.
type MockConnectionInfoKeeperMockRecorder struct {
	mock *MockConnectionInfoKeeper
}

// NewMockConnectionInfoKeeper creates a new mock instance.
func NewMockConnectionInfoKeeper(ctrl *gomock.Controller) *MockConnectionInfoKeeper {
	mock := &MockConnectionInfoKeeper{ctrl: ctrl}
	mock.recorder = &MockConnectionInfoKeeperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConnectionInfoKeeper) EXPECT() *MockConnectionInfoKeeperMockRecorder {
	return m.recorder
}

// AddDateOfLastVisit mocks base method.
func (m *MockConnectionInfoKeeper) AddDateOfLastVisit(arg0 context.Context, arg1 string, arg2 time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddDateOfLastVisit", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddDateOfLastVisit indicates an expected call of AddDateOfLastVisit.
func (mr *MockConnectionInfoKeeperMockRecorder) AddDateOfLastVisit(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddDateOfLastVisit", reflect.TypeOf((*MockConnectionInfoKeeper)(nil).AddDateOfLastVisit), arg0, arg1, arg2)
}

// GetDateOfLastVisit mocks base method.
func (m *MockConnectionInfoKeeper) GetDateOfLastVisit(arg0 context.Context, arg1 string) (time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDateOfLastVisit", arg0, arg1)
	ret0, _ := ret[0].(time.Time)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDateOfLastVisit indicates an expected call of GetDateOfLastVisit.
func (mr *MockConnectionInfoKeeperMockRecorder) GetDateOfLastVisit(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDateOfLastVisit", reflect.TypeOf((*MockConnectionInfoKeeper)(nil).GetDateOfLastVisit), arg0, arg1)
}
